### ISSUE TITLE
Update Elixir version to the latest

### ISSUE THREAD

**Issue by lucca65** [cambiatus/backend#49]
make sure our docker build process via `make build` still working properly

#### TODO
- [x] Test locally
- [ ] Update elixir version to 1.9 in staging
- [ ] Update CI config
- [ ] Update elixir version in prod

**Comment by lucca65** [comment]
done on #143
